// -*- C++ -*-
//
// generated by wxGlade 1.1.0pre on Fri Dec 17 03:27:41 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "pch.h"
#include "degenerate_ui.h"




MainFrame::MainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    SetSize(wxSize(895, 506));
    SetTitle(_("frame"));
    mainPanel = new wxPanel(this, wxID_ANY);
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    mainSpliter = new wxSplitterWindow(mainPanel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER|wxSP_LIVE_UPDATE);
    mainSpliter->SetMinimumPaneSize(300);
    mainSizer->Add(mainSpliter, 1, wxEXPAND, 0);
    leftPanel = new wxPanel(mainSpliter, wxID_ANY);
    wxBoxSizer* leftSizer = new wxBoxSizer(wxVERTICAL);
    leftSpliter = new wxSplitterWindow(leftPanel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D|wxSP_BORDER|wxSP_LIVE_UPDATE);
    leftSpliter->SetMinimumPaneSize(20);
    leftSizer->Add(leftSpliter, 1, wxEXPAND, 0);
    inputPanel = new wxPanel(leftSpliter, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_THEME|wxTAB_TRAVERSAL);
    wxBoxSizer* inputSizer = new wxBoxSizer(wxVERTICAL);
    wxStaticText* sequenceLabel = new wxStaticText(inputPanel, wxID_ANY, _("Sequence:"));
    inputSizer->Add(sequenceLabel, 0, wxBOTTOM|wxLEFT|wxTOP, 5);
    inputCtrl = new wxTextCtrl(inputPanel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    inputSizer->Add(inputCtrl, 1, wxALL|wxEXPAND, 5);
    generateButton = new wxButton(inputPanel, wxID_ANY, _("Generate"));
    inputSizer->Add(generateButton, 0, wxBOTTOM|wxLEFT, 5);
    resultsPanel = new wxPanel(leftSpliter, wxID_ANY);
    wxBoxSizer* resultsSizer = new wxBoxSizer(wxVERTICAL);
    wxStaticText* resultsLabel = new wxStaticText(resultsPanel, wxID_ANY, _("Results:"));
    resultsSizer->Add(resultsLabel, 0, wxBOTTOM|wxLEFT|wxTOP, 5);
    generationResultsTable = new wxListCtrl(resultsPanel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLC_HRULES|wxLC_REPORT|wxLC_VRULES);
    generationResultsTable->AppendColumn(_("Property"), wxLIST_FORMAT_LEFT, -1);
    generationResultsTable->AppendColumn(_("Value"), wxLIST_FORMAT_LEFT, 355);
    resultsSizer->Add(generationResultsTable, 1, wxEXPAND, 0);
    listPanel = new wxPanel(mainSpliter, wxID_ANY);
    
    resultsPanel->SetSizer(resultsSizer);
    inputPanel->SetSizer(inputSizer);
    leftSpliter->SplitHorizontally(inputPanel, resultsPanel);
    leftPanel->SetSizer(leftSizer);
    mainSpliter->SplitVertically(leftPanel, listPanel);
    mainPanel->SetSizer(mainSizer);
    Layout();
}